name: Build, Deploy and Deactivate ACA revision

on:
  pull_request:
    types: [opened, synchronize, closed]

permissions:
  # for `create-or-update-comment` action
  pull-requests: write
  issues: write

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    name: Build and Deploy Job

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch_name

      - name: Set repository name to env
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
          echo "SHORT_HASH=${COMMIT_HASH:0:7}" >> $GITHUB_ENV
        env:
          COMMIT_HASH: ${{ github.event.pull_request.head.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPLE }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPLE_PASSWORD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ secrets.CONTAINER_REGISTRY_NAME }}
          repository: ${{ secrets.REPOSITORY_NAME }}
          image: antonigaudi
          branch: ${{ steps.extract_branch_name.outputs.BRANCH }}
          tag: ${{ github.event.pull_request.head.sha }}

      - name: Add revision to ACA
        uses: Azure/aca-review-apps@v0.2.0
        id: aca_new_revision
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP_NAME }}
          name: ${{ secrets.CONTAINER_APP_NAME }}
          revision-name-suffix: ${{ env.SHORT_HASH }}
          image: ${{ secrets.CONTAINER_REGISTRY_SERVER }}/${{ secrets.REPOSITORY_NAME }}/antonigaudi:${{ github.event.pull_request.head.sha }}

      - name: Add new comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Revision ${{ secrets.CONTAINER_APP_NAME }}--${{ env.SHORT_HASH }} is created.
            ${{ steps.aca_new_revision.outputs.app-url }}

  close_pull_request_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Close Pull Request Job

    steps:
      - name: Set short version of Commit hash  to env
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
          echo "SHORT_HASH=${COMMIT_HASH:0:7}" >> $GITHUB_ENV
        env:
          COMMIT_HASH: |
            ${{
              github.event.action == 'closed' && github.event.pull_request.head.sha ||
              github.event.action == 'synchronize' && github.event.before
            }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deactivate Preview revision on ACA
        uses: Azure/aca-review-apps@v0.2.0
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP_NAME }}
          name: ${{ secrets.CONTAINER_APP_NAME }}
          revision-name-suffix: ${{ env.SHORT_HASH }}
          deactivate-revision-mode: true
          image: "THIS_VALUE_IS_IGNORED_IN_DEACTIVATION_MODE"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Revision ${{ secrets.CONTAINER_APP_NAME }}--${{ env.SHORT_HASH }} is created.

      - name: Add new comment to PR
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            Revision ${{ env.CONTAINERAPP_NAME }}--${{ env.SHORT_HASH }} is deactivated.
